### ISSUE TITLE
MODULE_NOT_FOUND in tesseract.js electron sample

### ISSUE THREAD

**Issue by jemagid** [jeromewu/tesseract.js-electron#6]
```
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'K:\ar_copy\file:\K:\ar_copy\node_modules\tesseract.js\src\worker-script\n
ode\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1056:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

This error shows on both the default example that was given and a control application that I made. The error is the exact same for both applications.

**Comment by eisneim** [comment]
same here, 2021-3-31
